version: '3.4'

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        command: npm run start:dev
        ports:
            - 3000:3000
        networks:
            - main-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - db
    db:
        container_name: db
        image: mysql:8
        ports:
            - 33060:3306
        restart: always
        command: |
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
            --max_allowed_packet=256MB
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE?err}
            MYSQL_USER: ${DB_USERNAME?err}
            MYSQL_PASSWORD: ${DB_PASSWORD?err}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD?err}
        volumes:
            - mysql_data:/var/lib/mysql

networks:
    main-network:

volumes:
    mysql_data:
